/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

import DAO.HangHoaDAO;
import POJO.HangHoa;
import DAO.HoaDonDAO;
import POJO.HoaDon;
import DAO.BanDAO;
import POJO.Ban;
import DAO.ChiTietHoaDonDAO;
import DAO.NguyenLieuDao;
import DAO.SQLServerProvider;
import POJO.ChiTietHoaDon;
import POJO.ChiTietNLHH;
import POJO.NguyenLieu;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.GridLayout;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import java.util.Date;
import java.util.Vector;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.border.TitledBorder;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Admin
 */
public class CustomerOderGUI extends javax.swing.JPanel {

    ArrayList<HangHoa> dsHangHoa = new ArrayList<>();
    ArrayList<Ban> dsBan = new ArrayList<>();
    ArrayList<ChiTietHoaDon> dsChiTietHoaDon = new ArrayList<>();

    /**
     * Creates new form CustomerOderGUI
     */
    public CustomerOderGUI() {
        initComponents();
        jPanel6.setLayout(new BorderLayout());
        dsHangHoa = HangHoaDAO.layDanhSachHangHoa();
        jPanel6.add(createHangHoaPanel(dsHangHoa), BorderLayout.CENTER);
        setVisible(true);
        //HIển thị combobox bàn
        hienThiComboBoxBan();
        cbbBan.setSelectedIndex(3);
        cbbBan.setSelectedIndex(0);
        //hienThiChiTietHoaDon();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtTimKiemHangHoa = new javax.swing.JTextField();
        btnTimKiemHangHoa = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        btnThanhToan = new javax.swing.JButton();
        txtTienKhachTra = new javax.swing.JTextField();
        txtTienThoi = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtTongTienSanPham = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        btnTinhTienThoi = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        cbbBan = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbChiTietHoaDon = new javax.swing.JTable();
        btnXoaMon = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        txtSoLuongCuaMon = new javax.swing.JTextField();
        btnCapNhatSoLuongMon = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(17, 66, 161));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Menu Order");

        btnTimKiemHangHoa.setText("Tìm");
        btnTimKiemHangHoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimKiemHangHoaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addComponent(txtTimKiemHangHoa, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnTimKiemHangHoa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(127, 127, 127))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtTimKiemHangHoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTimKiemHangHoa))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(231, 242, 255));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Danh sách nước");

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 204)));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 723, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(278, 278, 278)
                .addComponent(jLabel2)
                .addContainerGap(350, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel4.setBackground(new java.awt.Color(231, 242, 255));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Order");

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 153)));

        btnThanhToan.setBackground(new java.awt.Color(17, 66, 161));
        btnThanhToan.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnThanhToan.setForeground(new java.awt.Color(255, 255, 255));
        btnThanhToan.setText("Thanh toán");
        btnThanhToan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThanhToanActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("Tiền thối");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setText("Tiền khách trả");

        txtTongTienSanPham.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTongTienSanPhamActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("Tổng tiền sản phẩm'");

        btnTinhTienThoi.setBackground(new java.awt.Color(17, 66, 161));
        btnTinhTienThoi.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnTinhTienThoi.setForeground(new java.awt.Color(255, 255, 255));
        btnTinhTienThoi.setText("Tính tiền thối");
        btnTinhTienThoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTinhTienThoiActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 0, 51));
        jLabel5.setText("VND");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 0, 51));
        jLabel10.setText("VND");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 0, 51));
        jLabel11.setText("VND");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnTinhTienThoi, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(txtTongTienSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel11))
                            .addComponent(jLabel4)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(txtTienKhachTra, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addComponent(txtTienThoi, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel10))
                                    .addComponent(jLabel6)))))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addComponent(btnThanhToan, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTongTienSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel6))
                .addGap(2, 2, 2)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTienKhachTra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTienThoi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnTinhTienThoi, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(73, 73, 73)
                .addComponent(btnThanhToan, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(75, Short.MAX_VALUE))
        );

        cbbBan.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbbBanItemStateChanged(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setText("Chọn bàn");

        tbChiTietHoaDon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbChiTietHoaDon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbChiTietHoaDonMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tbChiTietHoaDon);

        btnXoaMon.setBackground(new java.awt.Color(17, 66, 161));
        btnXoaMon.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnXoaMon.setForeground(new java.awt.Color(255, 255, 255));
        btnXoaMon.setText("Xóa món");
        btnXoaMon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaMonActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setText("Số lượng của món :");

        btnCapNhatSoLuongMon.setBackground(new java.awt.Color(17, 66, 161));
        btnCapNhatSoLuongMon.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnCapNhatSoLuongMon.setForeground(new java.awt.Color(255, 255, 255));
        btnCapNhatSoLuongMon.setText("Cập nhật số lượng món");
        btnCapNhatSoLuongMon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCapNhatSoLuongMonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cbbBan, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(184, 184, 184)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 652, Short.MAX_VALUE)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtSoLuongCuaMon, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(btnCapNhatSoLuongMon)
                                        .addGap(18, 18, 18)))
                                .addComponent(btnXoaMon)))))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbbBan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtSoLuongCuaMon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnXoaMon)
                    .addComponent(btnCapNhatSoLuongMon))
                .addGap(34, 34, 34)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtTongTienSanPhamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTongTienSanPhamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTongTienSanPhamActionPerformed

    private void cbbBanItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbbBanItemStateChanged
        // TODO add your handling code here:
        int MaHoaDonHienTai;
        String tenBan = cbbBan.getSelectedItem().toString();
        Ban ban = BanDAO.timBanTheoTen(tenBan);
        MaHoaDonHienTai = ban.getHdHienTai();
        hienThiChiTietHoaDon(MaHoaDonHienTai);
        hienThiThanhToanHoaDon();
    }//GEN-LAST:event_cbbBanItemStateChanged

    private void hienThiThanhToanHoaDon() {
        String tenBan = cbbBan.getSelectedItem().toString();
        Ban ban = BanDAO.timBanTheoTen(tenBan);
        int maHoaDonHienTai = ban.getHdHienTai();
        HoaDon hd = HoaDonDAO.searchHoaDonTheoMaHoaDon(maHoaDonHienTai);
        txtTongTienSanPham.setText(String.valueOf(hd.getTongTien()));
    }

    private void tbChiTietHoaDonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbChiTietHoaDonMouseClicked
        // TODO add your handling code here:
        int row = tbChiTietHoaDon.getSelectedRow();
        txtSoLuongCuaMon.setText(tbChiTietHoaDon.getValueAt(row, 2).toString());
        int soLuong = Integer.parseInt(txtSoLuongCuaMon.getText());
    }//GEN-LAST:event_tbChiTietHoaDonMouseClicked

    private void btnXoaMonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaMonActionPerformed
        // TODO add your handling code here:
        String tenBan = cbbBan.getSelectedItem().toString();
        Ban ban = BanDAO.timBanTheoTen(tenBan);
        int MaHoaDonHienTai = ban.getHdHienTai();
        //Lấy mã món đang chọn
        int row = tbChiTietHoaDon.getSelectedRow();
        int maMonHienTai = Integer.parseInt(tbChiTietHoaDon.getValueAt(row, 0).toString());
        boolean check = ChiTietHoaDonDAO.deleteChiTietHoaDon(new ChiTietHoaDon(MaHoaDonHienTai, maMonHienTai, 1, 0));
        if (check) {
            hienThiChiTietHoaDon(MaHoaDonHienTai);
            hienThiThanhToanHoaDon();
        }
    }//GEN-LAST:event_btnXoaMonActionPerformed

    private void btnCapNhatSoLuongMonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCapNhatSoLuongMonActionPerformed
        // TODO add your handling code here:
        String tenBan = cbbBan.getSelectedItem().toString();
        Ban ban = BanDAO.timBanTheoTen(tenBan);
        int MaHoaDonHienTai = ban.getHdHienTai();
        //Lấy mã món đang chọn
        int row = tbChiTietHoaDon.getSelectedRow();
        int maMonHienTai = Integer.parseInt(tbChiTietHoaDon.getValueAt(row, 0).toString());
        ChiTietHoaDon cthd = ChiTietHoaDonDAO.searchChiTietHoaDon(MaHoaDonHienTai, maMonHienTai);
        int soLuongMoi = Integer.parseInt(txtSoLuongCuaMon.getText());
        cthd.setSoLuong(soLuongMoi);
        boolean check = ChiTietHoaDonDAO.updatechiTietHoaDon(cthd);
        if (check) {
            hienThiChiTietHoaDon(MaHoaDonHienTai);
            hienThiThanhToanHoaDon();
        }
    }//GEN-LAST:event_btnCapNhatSoLuongMonActionPerformed

    private void btnTimKiemHangHoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimKiemHangHoaActionPerformed
        // TODO add your handling code here:
        String chuoiTimKiem = txtTimKiemHangHoa.getText();
        HangHoa fake = new HangHoa();
        fake.setMaLH(1);
        fake.setTenHH(chuoiTimKiem);
        dsHangHoa.clear();
        dsHangHoa = HangHoaDAO.searchHangHoa(fake);

        // Xóa tất cả các thành phần cũ trong jPanel6
        jPanel6.removeAll();

        // Thêm các thành phần mới vào jPanel6
        jPanel6.add(createHangHoaPanel(dsHangHoa), BorderLayout.CENTER);

        // Cập nhật lại giao diện
        jPanel6.revalidate();
        jPanel6.repaint();

    }//GEN-LAST:event_btnTimKiemHangHoaActionPerformed

    private void btnTinhTienThoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTinhTienThoiActionPerformed
        // TODO add your handling code here:
        int tongTien = Integer.parseInt(txtTongTienSanPham.getText());
        int tienKhachDua = Integer.parseInt(txtTienKhachTra.getText());
        int tienThua = tienKhachDua - tongTien;
        txtTienThoi.setText(String.valueOf(tienThua));
    }//GEN-LAST:event_btnTinhTienThoiActionPerformed

    private void btnThanhToanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThanhToanActionPerformed
        String tenBan = cbbBan.getSelectedItem().toString();
        Ban ban = BanDAO.timBanTheoTen(tenBan);
        int MaHDHT = ban.getHdHienTai();
        
        //Lấy HoaDon từ mahd
        HoaDon hd = HoaDonDAO.searchHoaDonTheoMaHoaDon(MaHDHT);
        
        //Cập nhật số tiền thanh toán
        hd.setSoTienThanhToan(hd.getTongTien());
        HoaDonDAO.updateNhapHang(hd);

        // Kiểm tra xem người dùng đã điền thông tin vào trường txtTienKhachTra chưa
        if (txtTienKhachTra.getText().isEmpty()) {
            // Nếu chưa điền, hiển thị thông báo và không thực hiện thanh toán
            JOptionPane.showMessageDialog(this, "Vui lòng nhập số tiền khách trả.");
            return; // Thoát khỏi phương thức
        }
        
        if (ban.getTrangThai().equals("Trong")) {
            // Nếu chưa điền, hiển thị thông báo và không thực hiện thanh toán
            JOptionPane.showMessageDialog(this, "Bàn trống");
            return; // Thoát khỏi phương thức
        }

        //Lấy danh sách hàng hóa của bàn đó
        ArrayList<ChiTietHoaDon> dsChiTietHoaDon = ChiTietHoaDonDAO.layDanhSachChiTietHoaDon(MaHDHT);
        for (ChiTietHoaDon item : dsChiTietHoaDon) {
            HangHoa hangHoa = HangHoaDAO.searchHangHoaTheoma(item.getMaHH());

            //Lấy danh sách nguyên liệu đã dùng và trừ vào bảng NGUYENLIEU
            ArrayList<ChiTietNLHH> dsChiTietNLHH = NguyenLieuDao.layDanhSachNguyenLieuTheoHangHoa(hangHoa.getMaHH());

            for (ChiTietNLHH ctnlhh : dsChiTietNLHH) {
                //Lấy NguyenLieu dựa vào Mã nguyên liệu
                NguyenLieu nguyenLieu = NguyenLieuDao.layNguyenLieuTheoMa(ctnlhh.getMaNL());
                float SoLuong = ctnlhh.getSoLuong() * item.getSoLuong();
                float SoLuongNew = nguyenLieu.getSoLuongTon() - SoLuong;
                nguyenLieu.setSoLuongTon(SoLuongNew);
                NguyenLieuDao.updateNguyenLieu(nguyenLieu);
            }
        }
        //Set giá trị TrangThai = "Trống"
        ban.setTrangThai("Trong");
        //Set HDHienTai =null;
        ban.setHdHienTai(-1);
        //Cập nhật Trạng thái: Trống, HDHienTai = null
        BanDAO.updateBan(ban);
        
        //Load lại trang
        cbbBan.setSelectedIndex(0);
        hienThiChiTietHoaDon(-1);
        hienThiThanhToanHoaDon();
        
        txtTienKhachTra.setText("");
        txtTienThoi.setText("");
        txtTimKiemHangHoa.setText("");
        txtTongTienSanPham.setText("");
    }//GEN-LAST:event_btnThanhToanActionPerformed
    void hienThiComboBoxBan() {
        dsBan = BanDAO.layDanhSachBan();
        for (Ban item : dsBan) {
            //if (item.getTrangThai().equals("Trống")) {
            cbbBan.addItem(item.getTenBan());
            //}
        }
    }

    void hienThiChiTietHoaDon(int maHD) {
        dsChiTietHoaDon = ChiTietHoaDonDAO.layDanhSachChiTietHoaDon(maHD);
        DefaultTableModel dtm = new DefaultTableModel();
        String[] tieuDe = {"Mã hàng", "Tên hàng", "Số lượng", "Đơn giá", "Thành tiền"};
        dtm.setColumnIdentifiers(tieuDe);
        for (ChiTietHoaDon hh : dsChiTietHoaDon) {
            Vector<Object> vector = new Vector<>();
            vector.add(hh.getMaHH());
            HangHoa hh1 = HangHoaDAO.searchHangHoaTheoma(hh.getMaHH());
            vector.add(hh1.getTenHH());
            vector.add(hh.getSoLuong());
            vector.add(hh1.getGiaSP());
            vector.add(hh.getThanhTien());
            dtm.addRow(vector);
        }
        tbChiTietHoaDon.setModel(dtm);
    }

    public JScrollPane createHangHoaPanel(ArrayList<HangHoa> dsHangHoa) {
        JPanel mainPanel = new JPanel();
        mainPanel.setLayout(new GridLayout(0, 2, 10, 10)); // Sửa GridLayout để hiển thị 2 cột

        try {
            //dsHangHoa = HangHoaDAO.layDanhSachHangHoa();

            for (HangHoa hangHoa : dsHangHoa) {
                int maHH = hangHoa.getMaHH();
                int maLH = hangHoa.getMaLH();
                String tenHH = hangHoa.getTenHH();
                String hinhAnh = "Images/" + hangHoa.getHinhAnh();
                int giaSP = hangHoa.getGiaSP();

                JPanel panel = new JPanel(new BorderLayout());
                panel.setBorder(new TitledBorder("Hàng hóa: " + tenHH));

                JLabel imgLabel = new JLabel();
                ImageIcon icon = new ImageIcon(getClass().getClassLoader().getResource(hinhAnh));
                Image img = icon.getImage().getScaledInstance(200, 200, Image.SCALE_SMOOTH);
                imgLabel.setIcon(new ImageIcon(img));
                panel.add(imgLabel, BorderLayout.CENTER); // Đưa ảnh vào giữa panel

                JPanel infoPanel = new JPanel(new GridLayout(0, 1));
                infoPanel.add(new JLabel("Mã HH: " + maHH));
                infoPanel.add(new JLabel("Tên sản phẩm: " + tenHH)); // Thêm tên sản phẩm vào panel thông tin
                infoPanel.add(new JLabel("Giá SP: " + giaSP));
                JButton addButton = new JButton("Thêm vào danh sách ORDER");
                addButton.setBackground(new Color(17, 66, 161)); // Đổi màu nút
                addButton.setForeground(Color.WHITE); // Đổi màu chữ
                addButton.addActionListener(new ActionListener() {
                    @Override
                    public void actionPerformed(ActionEvent e) {
                        // Lấy ra panel chứa nút được nhấn
                        JPanel panel = (JPanel) addButton.getParent().getParent();
                        // Lấy ra panel thông tin sản phẩm từ panel chứa nút
                        JPanel infoPanel = (JPanel) panel.getComponent(1);
                        // Lấy ra thông tin sản phẩm từ panel thông tin
                        JLabel maHHLabel = (JLabel) infoPanel.getComponent(0); // Giả sử label đầu tiên chứa mã hàng hóa
                        String maHH = maHHLabel.getText().replace("Mã HH: ", ""); // Loại bỏ tiền tố "Mã HH: "
                        // Hiển thị hoặc sử dụng mã hàng hóa ở đây
                        int maHHDaLay = Integer.parseInt(maHH);
                        //Lấy giá trị bàn đang chọn trong combobox
                        int MaHoaDonHienTai;
                        String tenBan = cbbBan.getSelectedItem().toString();
                        Ban ban = BanDAO.timBanTheoTen(tenBan);
                        MaHoaDonHienTai = ban.getHdHienTai();
                        if (ban.getTrangThai().equals("Trong")) {
                            //Nếu bàn trống tạo mới 1 cái hóa đơn thêm vào hóa đơn
                            HoaDon hdTemp = new HoaDon();
                            hdTemp.setNgayXuatHD(new Date());
                            hdTemp.setMaNV(DAO.DataHolder.getMaNV());
                            hdTemp.setMaBan(ban.getMaBan());
                            hdTemp.setMaKH(1);
                            HoaDonDAO.insertHoaDon(hdTemp);
                            //Lấy mã hóa đơn mới vừa thêm vào
                            int mahd = HoaDonDAO.layMaHoaDonCuoiCung();
                            //Sau đó cập nhật giá trị bàn rồi lưu thay đổi
                            ban.setTrangThai("Dang dung");
                            ban.setHdHienTai(mahd);
                            BanDAO.updateBan(ban);
                            //Tạo chi tiết hóa đơn rồi thêm vào hóa đơn đó
                            ChiTietHoaDon cthd = new ChiTietHoaDon(mahd, maHHDaLay, 1, 0);
                            ChiTietHoaDonDAO.insertChiTietHoaDon(cthd);
                            //Hiển thị chi tiết hóa đơn
                            hienThiChiTietHoaDon(mahd);
                            hienThiThanhToanHoaDon();
                        } else {
                            //Bàn đã có hóa đơn
                            //Nếu món chưa có trong hóa đơn
                            if (ChiTietHoaDonDAO.kiemTraTonTaiMaMon(MaHoaDonHienTai, maHHDaLay) == false) {
                                //Tạo chi tiết hóa đơn tương ứng hóa đơn đang có
                                ChiTietHoaDon cthd = new ChiTietHoaDon(MaHoaDonHienTai, maHHDaLay, 1, 0);
                                ChiTietHoaDonDAO.insertChiTietHoaDon(cthd);
                            } else //đã có món này tăng số lượng lên + 1
                            {
                                ChiTietHoaDon cthd = ChiTietHoaDonDAO.searchChiTietHoaDon(MaHoaDonHienTai, maHHDaLay);
                                cthd.setSoLuong(cthd.getSoLuong() + 1);
                                ChiTietHoaDonDAO.updatechiTietHoaDon(cthd);
                            }

                            //Hiển thị chi tiết hóa đơn
                            hienThiChiTietHoaDon(MaHoaDonHienTai);
                            hienThiThanhToanHoaDon();
                        }

                        System.out.println("Mã hàng hóa: " + maHHDaLay);
                    }
                });
                infoPanel.add(addButton); // Thêm nút vào panel thông tin
                panel.add(infoPanel, BorderLayout.SOUTH); // Đưa panel thông tin vào dưới cùng

                mainPanel.add(panel);
            }

        } catch (Exception e) {
            e.printStackTrace();
            System.out.println("Lỗi khi tải dữ liệu: " + e.getMessage());
        }

        return new JScrollPane(mainPanel);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCapNhatSoLuongMon;
    private javax.swing.JButton btnThanhToan;
    private javax.swing.JButton btnTimKiemHangHoa;
    private javax.swing.JButton btnTinhTienThoi;
    private javax.swing.JButton btnXoaMon;
    private javax.swing.JComboBox<String> cbbBan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable tbChiTietHoaDon;
    private javax.swing.JTextField txtSoLuongCuaMon;
    private javax.swing.JTextField txtTienKhachTra;
    private javax.swing.JTextField txtTienThoi;
    private javax.swing.JTextField txtTimKiemHangHoa;
    private javax.swing.JTextField txtTongTienSanPham;
    // End of variables declaration//GEN-END:variables
}
